<a href="https://colab.research.google.com/github/Mohammedaslaan/Machine-Learning-Projects/blob/main/Submarine_Rock_Vs_Mine_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/Copy of sonar data.csv')

In [ ]:
df.head()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
0,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
1,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
2,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
3,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
4,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062,R

In [ ]:
df.shape

(207, 61)

In [ ]:
df.describe()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
count,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,...,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000
mean,0.029208,0.038443,0.043837,0.054053,0.075105,0.104599,0.121591,0.134677,0.177361,0.208245,...,0.016034,0.013472,0.010729,0.010917,0.009300,0.008181,0.007771,0.007947,0.007936,0.006523
std,0.023038,0.033040,0.038521,0.046583,0.055669,0.059247,0.061897,0.085340,0.118311,0.134741,...,0.012027,0.009628,0.007071,0.007310,0.007103,0.005719,0.005756,0.006485,0.006196,0.005038
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013300,0.016400,0.018900,0.024450,0.037700,0.066950,0.080600,0.080350,0.096750,0.111150,...,0.008350,0.007350,0.005050,0.005350,0.004100,0.004400,0.003700,0.003600,0.003650,0.003100
50%,0.022800,0.030800,0.034200,0.044100,0.062000,0.092100,0.105600,0.111900,0.152200,0.181000,...,0.013800,0.011500,0.009600,0.009300,0.007500,0.006800,0.005900,0.005800,0.006300,0.005300
75%,0.035800,0.048100,0.058200,0.065700,0.101050,0.134150,0.153050,0.169800,0.231500,0.269000,...,0.020700,0.016750,0.014900,0.014450,0.012100,0.010350,0.010350,0.010400,0.010350,0.008550
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0.0200  207 non-null    float64
 1   0.0371  207 non-null    float64
 2   0.0428  207 non-null    float64
 3   0.0207  207 non-null    float64
 4   0.0954  207 non-null    float64
 5   0.0986  207 non-null    float64
 6   0.1539  207 non-null    float64
 7   0.1601  207 non-null    float64
 8   0.3109  207 non-null    float64
 9   0.2111  207 non-null    float64
 10  0.1609  207 non-null    float64
 11  0.1582  207 non-null    float64
 12  0.2238  207 non-null    float64
 13  0.0645  207 non-null    float64
 14  0.0660  207 non-null    float64
 15  0.2273  207 non-null    float64
 16  0.3100  207 non-null    float64
 17  0.2999  207 non-null    float64
 18  0.5078  207 non-null    float64
 19  0.4797  207 non-null    float64
 20  0.5783  207 non-null    float64
 21  0.5071  207 non-null    float64
 22  0.4328  207 non-null    float64
 23  0.5550  207 non-null    float64
 24  0.6711  207 non-null    float64
 25  0.6415  207 non-null    float64
 26  0.7104  207 non-null    float64
 27  0.8080  207 non-null    float64
 28  0.6791  207 non-null    float64
 29  0.3857  207 non-null    float64
 30  0.1307  207 non-null    float64
 31  0.2604  207 non-null    float64
 32  0.5121  207 non-null    float64
 33  0.7547  207 non-null    float64
 34  0.8537  207 non-null    float64
 35  0.8507  207 non-null    float64
 36  0.6692  207 non-null    float64
 37  0.6097  207 non-null    float64
 38  0.4943  207 non-null    float64
 39  0.2744  207 non-null    float64
 40  0.0510  207 non-null    float64
 41  0.2834  207 non-null    float64
 42  0.2825  207 non-null    float64
 43  0.4256  207 non-null    float64
 44  0.2641  207 non-null    float64
 45  0.1386  207 non-null    float64
 46  0.1051  207 non-null    float64
 47  0.1343  207 non-null    float64
 48  0.0383  207 non-null    float64
 49  0.0324  207 non-null    float64
 50  0.0232  207 non-null    float64
 51  0.0027  207 non-null    float64
 52  0.0065  207 non-null    float64
 53  0.0159  207 non-null    float64
 54  0.0072  207 non-null    float64
 55  0.0167  207 non-null    float64
 56  0.0180  207 non-null    float64
 57  0.0084  207 non-null    float64
 58  0.0090  207 non-null    float64
 59  0.0032  207 non-null    float64
 60  R       207 non-null    object
dtypes: float64(60), object(1)
memory usage: 98.8+ KB

In [ ]:
df.columns

Index(['0.0200', '0.0371', '0.0428', '0.0207', '0.0954', '0.0986', '0.1539',
       '0.1601', '0.3109', '0.2111', '0.1609', '0.1582', '0.2238', '0.0645',
       '0.0660', '0.2273', '0.3100', '0.2999', '0.5078', '0.4797', '0.5783',
       '0.5071', '0.4328', '0.5550', '0.6711', '0.6415', '0.7104', '0.8080',
       '0.6791', '0.3857', '0.1307', '0.2604', '0.5121', '0.7547', '0.8537',
       '0.8507', '0.6692', '0.6097', '0.4943', '0.2744', '0.0510', '0.2834',
       '0.2825', '0.4256', '0.2641', '0.1386', '0.1051', '0.1343', '0.0383',
       '0.0324', '0.0232', '0.0027', '0.0065', '0.0159', '0.0072', '0.0167',
       '0.0180', '0.0084', '0.0090', '0.0032', 'R'],
      dtype='object')

In [ ]:
df['R'].unique()

array(['R', 'M'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
df['R'] = le.fit_transform(df['R'])

In [ ]:
df['R'].dtypes

dtype('int64')

In [ ]:
df['R']

0      1
1      1
2      1
3      1
4      1
      ..
202    0
203    0
204    0
205    0
206    0
Name: R, Length: 207, dtype: int64

In [ ]:
df.corr()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
0.0200,1.000000,0.736104,0.571706,0.490853,0.345744,0.238824,0.262095,0.356312,0.356822,0.318440,...,0.354348,0.310964,0.324101,0.311683,0.224784,0.319663,0.368413,0.357611,0.346302,-0.270482
0.0371,0.736104,1.000000,0.779915,0.607297,0.419877,0.332319,0.279328,0.334747,0.317929,0.270787,...,0.435641,0.346259,0.384526,0.380188,0.263959,0.282822,0.353061,0.352260,0.359010,-0.231670
0.0428,0.571706,0.779915,1.000000,0.782662,0.546365,0.346271,0.190628,0.237974,0.253615,0.219641,...,0.395121,0.333124,0.367687,0.289754,0.289393,0.383945,0.334122,0.425100,0.374256,-0.192589
0.0207,0.490853,0.607297,0.782662,1.000000,0.729338,0.352901,0.248713,0.248131,0.252048,0.238136,...,0.372377,0.363470,0.337358,0.284345,0.287941,0.349411,0.345537,0.421410,0.399262,-0.247935
0.0954,0.345744,0.419877,0.546365,0.729338,1.000000,0.597438,0.334831,0.203590,0.176522,0.183240,...,0.269478,0.316412,0.204402,0.197098,0.197829,0.218004,0.238749,0.290793,0.255220,-0.224809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.0180,0.319663,0.282822,0.383945,0.349411,0.218004,0.163433,0.183382,0.266743,0.186347,0.141211,...,0.202905,0.315943,0.358746,0.392768,0.509056,1.000000,0.513086,0.433130,0.295369,-0.010152
0.0084,0.368413,0.353061,0.334122,0.345537,0.238749,0.204027,0.242632,0.287568,0.232078,0.212272,...,0.310989,0.371290,0.404345,0.503677,0.465640,0.513086,1.000000,0.550223,0.330400,-0.185066
0.0090,0.357611,0.352260,0.425100,0.421410,0.290793,0.220678,0.183279,0.194209,0.096662,0.058260,...,0.300562,0.346915,0.447086,0.454032,0.431902,0.433130,0.550223,1.000000,0.644140,-0.132088
0.0032,0.346302,0.359010,0.374256,0.399262,0.255220,0.178027,0.224536,0.147350,0.099233,0.097528,...,0.192609,0.279412,0.286259,0.263791,0.356433,0.295369,0.330400,0.644140,1.000000,-0.086982
R,-0.270482,-0.231670,-0.192589,-0.247935,-0.224809,-0.132172,-0.117848,-0.191424,-0.329180,-0.342199,...,-0.284528,-0.139288,-0.186932,-0.094392,-0.138112,-0.010152,-0.185066,-0.132088,-0.086982,1.000000

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.drop('R',axis=1 )
y = df['R']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=1,test_size=0.1)

In [ ]:
x_train.shape

(186, 60)

In [ ]:
x_test.shape

(21, 60)

In [ ]:
y_train.shape

(186,)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
classifier = LogisticRegression()

In [ ]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
result = pd.DataFrame({
    'actual' : y_test,
    'predicted': y_pred
})

In [ ]:
result

     actual  predicted
186       0          0
155       0          0
165       0          0
200       0          0
58        1          1
34        1          0
151       0          0
18        1          0
202       0          0
62        1          1
4         1          1
47        1          1
110       0          0
205       0          0
105       0          1
172       0          0
31        1          1
198       0          0
33        1          1
40        1          1
175       0          0

In [ ]:

count = len(result[result['actual'] == result['predicted']])

In [ ]:
count

18

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,y_pred)

0.8571428571428571

In [ ]:
import numpy as np

s = "0.0164 0.0173 0.0347 0.007 0.0187 0.0671 0.1056 0.0697 0.0962 0.0251 0.0801 0.1056 0.1266 0.089 0.0198 0.1133 0.2826 0.3234 0.3238 0.4333 0.6068 0.7652 0.9203 0.9719 0.9207 0.7545 0.8289 0.8907 0.7309 0.6896 0.5829 0.4935 0.3101 0.0306 0.0244 0.1108 0.1594 0.1371 0.0696 0.0452 0.062 0.1421 0.1597 0.1384 0.0372 0.0688 0.0867 0.0513 0.0092 0.0198 0.0118 0.009 0.0223 0.0179 0.0084 0.0068 0.0032 0.0035 0.0056 0.004 R"

# Convert string to NumPy array
arr = np.fromstring(s, sep=' ')

pd.DataFrame(arr)

<ipython-input-47-bb2ddddcc770>:6: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  arr = np.fromstring(s, sep=' ')

         0
0   0.0164
1   0.0173
2   0.0347
3   0.0070
4   0.0187
5   0.0671
6   0.1056
7   0.0697
8   0.0962
9   0.0251
10  0.0801
11  0.1056
12  0.1266
13  0.0890
14  0.0198
15  0.1133
16  0.2826
17  0.3234
18  0.3238
19  0.4333
20  0.6068
21  0.7652
22  0.9203
23  0.9719
24  0.9207
25  0.7545
26  0.8289
27  0.8907
28  0.7309
29  0.6896
30  0.5829
31  0.4935
32  0.3101
33  0.0306
34  0.0244
35  0.1108
36  0.1594
37  0.1371
38  0.0696
39  0.0452
40  0.0620
41  0.1421
42  0.1597
43  0.1384
44  0.0372
45  0.0688
46  0.0867
47  0.0513
48  0.0092
49  0.0198
50  0.0118
51  0.0090
52  0.0223
53  0.0179
54  0.0084
55  0.0068
56  0.0032
57  0.0035
58  0.0056
59  0.0040

In [ ]:
import pandas as pd

data = {
    'Value': [
        0.0164, 0.0173, 0.0347, 0.0070, 0.0187, 0.0671, 0.1056, 0.0697, 0.0962, 0.0251,
        0.0801, 0.1056, 0.1266, 0.0890, 0.0198, 0.1133, 0.2826, 0.3234, 0.3238, 0.4333,
        0.6068, 0.7652, 0.9203, 0.9719, 0.9207, 0.7545, 0.8289, 0.8907, 0.7309, 0.6896,
        0.5829, 0.4935, 0.3101, 0.0306, 0.0244, 0.1108, 0.1594, 0.1371, 0.0696, 0.0452,
        0.0620, 0.1421, 0.1597, 0.1384, 0.0372, 0.0688, 0.0867, 0.0513, 0.0092, 0.0198,
        0.0118, 0.0090, 0.0223, 0.0179, 0.0084, 0.0068, 0.0032, 0.0035, 0.0056, 0.0040
    ]
}

df = pd.DataFrame(data)

df_transposed = df.transpose()

df_transposed

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
Value,0.0164,0.0173,0.0347,0.007,0.0187,0.0671,0.1056,0.0697,0.0962,0.0251,...,0.0118,0.009,0.0223,0.0179,0.0084,0.0068,0.0032,0.0035,0.0056,0.004

In [ ]:
classifier.predict(df_transposed)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])